export const browserCoreExamples = [
  "kolb-bot browser status",
  "kolb-bot browser start",
  "kolb-bot browser stop",
  "kolb-bot browser tabs",
  "kolb-bot browser open https://example.com",
  "kolb-bot browser focus abcd1234",
  "kolb-bot browser close abcd1234",
  "kolb-bot browser screenshot",
  "kolb-bot browser screenshot --full-page",
  "kolb-bot browser screenshot --ref 12",
  "kolb-bot browser snapshot",
  "kolb-bot browser snapshot --format aria --limit 200",
  "kolb-bot browser snapshot --efficient",
  "kolb-bot browser snapshot --labels",
];

export const browserActionExamples = [
  "kolb-bot browser navigate https://example.com",
  "kolb-bot browser resize 1280 720",
  "kolb-bot browser click 12 --double",
  'kolb-bot browser type 23 "hello" --submit',
  "kolb-bot browser press Enter",
  "kolb-bot browser hover 44",
  "kolb-bot browser drag 10 11",
  "kolb-bot browser select 9 OptionA OptionB",
  "kolb-bot browser upload /tmp/kolb-bot/uploads/file.pdf",
  'kolb-bot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "kolb-bot browser dialog --accept",
  'kolb-bot browser wait --text "Done"',
  "kolb-bot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "kolb-bot browser console --level error",
  "kolb-bot browser pdf",
];
