blank_issues_enabled: false
contact_links:
  - name: Onboarding
    url: https://github.com/kolbick/Kolb-Bot-Beta-
    about: "New to Kolb-Bot? Join Discord for setup guidance in #help."
  - name: Support
    url: https://github.com/kolbick/Kolb-Bot-Beta-
    about: "Get help from the Kolb-Bot community on Discord in #help."
