#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${KOLB_BOT_INSTALL_E2E_IMAGE:-${KOLB_BOT_INSTALL_E2E_IMAGE:-kolb-bot-install-e2e:local}}"
INSTALL_URL="${KOLB_BOT_INSTALL_URL:-${KOLB_BOT_INSTALL_URL:-https://kolb-bot.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
KOLB_BOT_E2E_MODELS="${KOLB_BOT_E2E_MODELS:-${KOLB_BOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e KOLB_BOT_INSTALL_URL="$INSTALL_URL" \
  -e KOLB_BOT_INSTALL_TAG="${KOLB_BOT_INSTALL_TAG:-${KOLB_BOT_INSTALL_TAG:-latest}}" \
  -e KOLB_BOT_E2E_MODELS="$KOLB_BOT_E2E_MODELS" \
  -e KOLB_BOT_INSTALL_E2E_PREVIOUS="${KOLB_BOT_INSTALL_E2E_PREVIOUS:-${KOLB_BOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e KOLB_BOT_INSTALL_E2E_SKIP_PREVIOUS="${KOLB_BOT_INSTALL_E2E_SKIP_PREVIOUS:-${KOLB_BOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
